services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - 127.0.0.1:${POSTGRES_EXTERNAL_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    env_file: .env
    ports:
      - 127.0.0.1:${KEYCLOAK_EXTERNAL_PORT}:8080
    depends_on:
      - postgres
    command: "start-dev"

volumes:
  pgdata:
