services:
  postgres:
    image: postgres:latest
    build:
      context: .
      dockerfile: docker/postgres.Dockerfile
    restart: unless-stopped
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:${POSTGRES_EXTERNAL_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]

volumes:
  pgdata:
